# common.sh - shared settings/helpers for the LMS dev scripts in this directory.
# Sourced by setup.sh, start.sh, stop.sh, etc. Override any variable via the environment.
# shellcheck shell=bash

DEV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$DEV_DIR/.." && pwd)"

LMS_VERSION="${LMS_VERSION:-9.1.1}"
LMS_TARBALL_URL="${LMS_TARBALL_URL:-https://downloads.lms-community.org/LyrionMusicServer_v${LMS_VERSION}/lyrionmusicserver-${LMS_VERSION}.tgz}"
# md5 published in https://lms-community.github.io/lms-server-repository/latest.xml ("src" entry)
if [[ -z "${LMS_TARBALL_MD5:-}" && "$LMS_VERSION" == "9.1.1" ]]; then LMS_TARBALL_MD5=11a05b8a79515fb4dfb303c5e0abc6e1; fi

LMS_BASE="${LMS_BASE:-/opt/lms-dev}"                 # everything LMS-related lives here
LMS_HOME="${LMS_HOME:-$LMS_BASE/server}"              # symlink -> lyrionmusicserver-<ver>
LMS_PREFS="${LMS_PREFS:-$LMS_BASE/prefs}"
LMS_CACHE="${LMS_CACHE:-$LMS_BASE/cache}"
LMS_RUN="${LMS_RUN:-$LMS_BASE/run}"                   # pid files
LOG_DIR="${LOG_DIR:-$DEV_DIR/logs}"                   # git-ignored
LMS_PORT="${LMS_PORT:-9000}"
LMS_RPC_URL="http://127.0.0.1:${LMS_PORT}/jsonrpc.js"

EGRESS_PORT="${EGRESS_PORT:-3129}"
PROXYCHAINS_CONF="${PROXYCHAINS_CONF:-$LMS_BASE/proxychains.conf}"

PLAYER_NAME="${PLAYER_NAME:-DevPlayer}"
PLAYER_MAC="${PLAYER_MAC:-00:00:00:00:00:01}"
# squeezelite writes 16-bit stereo PCM at a fixed 44.1kHz to stdout; pv throttles it to
# real time (44100 * 2 ch * 2 bytes) and discards it. See RUNBOOK "Audio output".
PLAYER_PCM_RATE="${PLAYER_PCM_RATE:-44100}"
PLAYER_BYTES_PER_SEC=$(( PLAYER_PCM_RATE * 4 ))

PLUGIN_NAME="${PLUGIN_NAME:-RTRFM}"
PLUGIN_SRC="${PLUGIN_SRC:-$REPO_DIR/RTRFM}"
LMS_PLUGIN_DIR="$LMS_HOME/Plugins"                    # scanned by LMS on Unix ($Bin/Plugins)

LMS_PIDFILE="$LMS_RUN/lms.pid"
EGRESS_PIDFILE="$LMS_RUN/egress-proxy.pid"
SQZ_PIDFILE="$LMS_RUN/squeezelite.pid"

mkdir -p "$LOG_DIR" "$LMS_RUN" 2>/dev/null || true

log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*" >&2; }
die() { log "ERROR: $*"; exit 1; }

# pid_alive <pidfile> : true if the pid in the file is a live process
pid_alive() {
  local f="$1" pid
  [[ -s "$f" ]] || return 1
  pid="$(cat "$f" 2>/dev/null)"
  [[ "$pid" =~ ^[0-9]+$ ]] && kill -0 "$pid" 2>/dev/null
}

# stop_pidfile <pidfile> <label> [timeout_s] [group] : SIGTERM (to the whole process
# group if 4th arg is "group"), wait, SIGKILL if needed, then sweep the process group
# (spawn_detached makes the pid the pgid).
stop_pidfile() {
  local f="$1" label="$2" t="${3:-20}" mode="${4:-}" pid i
  if ! pid_alive "$f"; then rm -f "$f"; return 0; fi
  pid="$(cat "$f")"
  log "stopping $label (pid $pid)"
  if [[ "$mode" == group ]]; then kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
  else kill -TERM "$pid" 2>/dev/null || true; fi
  for ((i = 0; i < t * 4; i++)); do kill -0 "$pid" 2>/dev/null || break; sleep 0.25; done
  if kill -0 "$pid" 2>/dev/null; then log "$label did not exit, sending SIGKILL"; kill -KILL "$pid" 2>/dev/null || true; fi
  kill -TERM -- "-$pid" 2>/dev/null || true
  rm -f "$f"
}

# rpc_raw <playerid|-> <json-array> : POST a slim.request, print the raw JSON response
rpc_raw() {
  local player="$1" cmd="$2" p
  if [[ "$player" == "-" || -z "$player" ]]; then p='"-"'; else p="\"$player\""; fi
  curl -sS -m "${RPC_TIMEOUT:-15}" --noproxy '*' -H 'Content-Type: application/json' \
    -d "{\"id\":1,\"method\":\"slim.request\",\"params\":[${p},${cmd}]}" "$LMS_RPC_URL"
}

rpc_up() { rpc_raw - '["serverstatus",0,0]' 2>/dev/null | grep -q '"result"'; }

# wait_until <timeout_s> <command...> : poll every 0.5s
wait_until() {
  local t="$1" i; shift
  for ((i = 0; i < t * 2; i++)); do "$@" && return 0; sleep 0.5; done
  return 1
}

# Write the proxychains config: every non-local TCP connect goes to the local egress-proxy.
write_proxychains_conf() {
  {
    echo "# generated by dev/common.sh - LMS/squeezelite egress via local egress-proxy.mjs"
    echo "strict_chain"
    echo "quiet_mode"
    echo "tcp_read_time_out 15000"
    echo "tcp_connect_time_out 8000"
    echo "localnet 127.0.0.0/255.0.0.0"
    echo "localnet 10.0.0.0/255.0.0.0"
    echo "localnet 172.16.0.0/255.240.0.0"
    echo "localnet 192.168.0.0/255.255.0.0"
    local ip
    for ip in $(hostname -I 2>/dev/null); do
      [[ "$ip" == *.* ]] && echo "localnet $ip/255.255.255.255"
    done
    echo "[ProxyList]"
    echo "http 127.0.0.1 $EGRESS_PORT"
  } > "$PROXYCHAINS_CONF"
}

# spawn_detached <pidfile> <logfile> <cmd...> : run cmd in its own session (survives the
# calling shell), stdout/stderr appended to logfile; pidfile gets the real pid, which is
# also the process-group id (so stop can kill children too).
spawn_detached() {
  local pidfile="$1" logfile="$2"; shift 2
  rm -f "$pidfile"
  setsid -f bash -c 'echo $$ >"$0"; exec "$@"' "$pidfile" "$@" >>"$logfile" 2>&1 </dev/null
  wait_until 5 test -s "$pidfile" || die "failed to spawn $1"
}

require_installed() {
  [[ -f "$LMS_HOME/slimserver.pl" ]] || die "LMS not installed at $LMS_HOME - run dev/setup.sh"
  local c
  for c in node squeezelite proxychains4 pv curl jq; do
    command -v "$c" >/dev/null || die "'$c' missing - run dev/setup.sh"
  done
}

# ---- egress-proxy (local CONNECT helper, see egress-proxy.mjs) ----
start_egress() {
  if pid_alive "$EGRESS_PIDFILE"; then log "egress-proxy already running (pid $(cat "$EGRESS_PIDFILE"))"; return 0; fi
  log "starting egress-proxy on 127.0.0.1:$EGRESS_PORT (upstream ${HTTPS_PROXY:-DIRECT})"
  EGRESS_PORT="$EGRESS_PORT" spawn_detached "$EGRESS_PIDFILE" "$LOG_DIR/egress-proxy.log" \
    node "$DEV_DIR/egress-proxy.mjs"
  wait_until 10 curl -s -o /dev/null --noproxy '*' "http://127.0.0.1:$EGRESS_PORT/" || die "egress-proxy did not start; see $LOG_DIR/egress-proxy.log"
}
stop_egress() { stop_pidfile "$EGRESS_PIDFILE" egress-proxy 5; }

# ---- Lyrion Music Server (wrapped in proxychains4) ----
start_lms() {
  if pid_alive "$LMS_PIDFILE"; then log "LMS already running (pid $(cat "$LMS_PIDFILE"))"; return 0; fi
  write_proxychains_conf
  mkdir -p "$LMS_PREFS" "$LMS_CACHE" "$LMS_PLUGIN_DIR"
  log "starting LMS $LMS_VERSION on http://localhost:$LMS_PORT (logs: $LOG_DIR/server.log)"
  # --user root: LMS refuses plain root and would switch to 'nobody' (can't write our dirs).
  # shellcheck disable=SC2086
  ( cd "$LMS_HOME" && LANG=C.UTF-8 LC_ALL=C.UTF-8 spawn_detached "$LMS_PIDFILE" "$LOG_DIR/lms-stdout.log" \
      proxychains4 -q -f "$PROXYCHAINS_CONF" /usr/bin/perl slimserver.pl --user root \
      --prefsdir "$LMS_PREFS" --cachedir "$LMS_CACHE" --logdir "$LOG_DIR" \
      --pidfile "$LMS_PIDFILE" --httpport "$LMS_PORT" --charset utf8 ${LMS_EXTRA_ARGS:-} )
  if ! wait_until "${LMS_START_TIMEOUT:-120}" rpc_up; then
    tail -n 30 "$LOG_DIR/lms-stdout.log" >&2 || true
    die "LMS JSON-RPC did not answer on $LMS_RPC_URL"
  fi
  # first-run wizard off so the web UI goes straight to the player view
  rpc_raw - '["pref","wizardDone","1"]' >/dev/null
  log "LMS up: $(rpc_raw - '["serverstatus",0,0]' | jq -r '.result | "v\(.version), \(."player count") player(s)"')"
}
stop_lms() { stop_pidfile "$LMS_PIDFILE" LMS 30; }

# ---- squeezelite "DevPlayer" ----
start_player() {
  if pid_alive "$SQZ_PIDFILE"; then log "squeezelite already running (pid $(cat "$SQZ_PIDFILE"))"; return 0; fi
  log "starting squeezelite '$PLAYER_NAME' ($PLAYER_MAC), paced PCM -> /dev/null"
  # -o -      : PCM to stdout (there is no sound card); -a 16 : 16-bit little-endian
  # -r R-R -u mX : output ONLY rate R, async-resampling everything to it, so pv can
  #              throttle the pipe to exactly real time (R * 2ch * 2 bytes per second)
  # -Z 192000  : still advertise a realistic max rate to LMS (else LMS rejects 48kHz streams)
  # proxychains: lets squeezelite fetch directly-streamed URLs (LMS's default) too.
  spawn_detached "$SQZ_PIDFILE" "$LOG_DIR/squeezelite.log" bash -c "proxychains4 -q -f '$PROXYCHAINS_CONF' squeezelite \
      -n '$PLAYER_NAME' -m '$PLAYER_MAC' -s 127.0.0.1 -o - -a 16 \
      -r $PLAYER_PCM_RATE-$PLAYER_PCM_RATE -u mX -Z 192000 \
      -d all=info -f '$LOG_DIR/squeezelite.log' | pv -q -L $PLAYER_BYTES_PER_SEC >/dev/null"
  if ! wait_until 30 player_connected; then
    log "WARNING: $PLAYER_NAME not visible in LMS players list yet; see $LOG_DIR/squeezelite.log"
    return 1
  fi
  log "$PLAYER_NAME connected"
}
# the squeezelite wrapper (bash | pv) is a process-group leader: signal the whole group
stop_player() { stop_pidfile "$SQZ_PIDFILE" squeezelite 10 group; }
player_connected() {
  rpc_raw - '["players",0,50]' 2>/dev/null | jq -e --arg m "$PLAYER_MAC" \
    '.result.players_loop[]? | select(.playerid == $m and .connected == 1)' >/dev/null
}
